---
# This scripts checks to see if packages are installed.
- hosts: localhost
  vars:
    package_names:
      - vim
      - htop
      - git
      - curl
      - tmux
      - tree
      - wget
      - stow
      - python3-psutil
      - clamav
      - clamav-daemon
      - ubuntu-restricted-extras
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-plugins-good 
      - libavcodec-extra 
      - gstreamer1.0-libav 
      - chromium-codecs-ffmpeg-extra 
      - libdvd-pkg 
      - libfuse2 
      - virtualbox 
      - virtualbox-ext-pack 
      - xclip 
      - gimp 
      - vlc
      - ninja-build
      - gettext
      - cmake
      - unzip
      - build-essential
      - npm

  tasks:
    - name:
      ansible.builtin.package: 
        name: "{{ item }}"
        state: present
      check_mode: true
      loop: "{{ package_names }}"
      register: package_check

    - name: "Print execution results"
      debug:
        msg: "Package is installed"
      when: package_check is succeeded
