---
- hosts: localhost
  connection: local
  become: true

  # This installs the necessary apt packages
  tasks:
  - name: Installing apt packages
    package: 
      name: 
       - htop
       - git
       - curl
       - tmux
       - tree
       - wget
       - stow
       - python3-psutil
       - clamav
       - clamav-daemon
       - ubuntu-restricted-extras
       - gstreamer1.0-plugins-bad 
       - gstreamer1.0-plugins-ugly 
       - gstreamer1.0-plugins-good 
       - libavcodec-extra 
       - gstreamer1.0-libav 
       - chromium-codecs-ffmpeg-extra 
       - libdvd-pkg 
       - libfuse2 
       - virtualbox 
       - virtualbox-ext-pack 
       - xclip 
       - gimp 
       - vlc
       - ninja-build
       - gettext
       - cmake
       - unzip
       - build-essential
       - npm

    # Installs zsh if not already installed
  - name: Make sure that zsh is installed
    apt: 
     name: zsh
     state: present
     update_cache: yes
    become: true

    # Switches the default shell to zsh
    # Make sure to log back out and back in
  - name: Make sure zsh is the default shell 
    user:
      name: gato
      shell: "/usr/bin/zsh"
    become: true
    
    # Download Zsh
  - name: Download Oh My Zsh installation script
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install_ohmyzsh.sh

    # Run ZSH install script
  - name: Run Oh My Zsh installation script
    command: sh /tmp/install_ohmyzsh.sh --unattended
    register: ohmyzsh_result
    failed_when: "'FAILED' in ohmyzsh_result.stderr"

    # Copy the .zshrc file to home directory
  - name: copy .zshrc file
    copy: 
     src: files/zshrc
     dest: /home/gato/.zshrc
     owner: gato
     group: gato

    # Copy the .tmux.conf file to the home directory
  - name: copy .tmux.conf
    copy: 
     src: files/tmux.conf
     dest: /home/gato/.tmux.conf
     owner: gato
     group: gato

  vars:
    package_names:
      - vim
      - htop
      - git
      - curl
      - tmux
      - tree
      - wget
      - stow
      - python3-psutil
      - clamav
      - clamav-daemon
      - ubuntu-restricted-extras
      - gstreamer1.0-plugins-bad 
      - gstreamer1.0-plugins-ugly 
      - gstreamer1.0-plugins-good 
      - libavcodec-extra 
      - gstreamer1.0-libav 
      - chromium-codecs-ffmpeg-extra 
      - libdvd-pkg 
      - libfuse2 
      - virtualbox 
      - virtualbox-ext-pack 
      - xclip 
      - gimp 
      - vlc
      - ninja-build
      - gettext
      - cmake
      - unzip
      - build-essential
      - npm
      - zsh

    tasks:
      - name: "Check package installation"
        ansible.builtin.package: 
          name: "{{ item }}"
          state: present
        check_mode: true
        loop: "{{ package_names }}"
        register: package_check

      - name: "Print execution results"
        debug:
          msg: "Package is installed"
        when: package_check is succeeded
