---
- hosts: localhost
  connection: local
  become: true

  # This installs the necessary apt packages
  tasks:
  - name: Installing apt packages
    package: 
      name: 
       - htop
       - git
       - curl
       - tmux
       - tree
       - wget
       - stow
       - python3-psutil
       - clamav
       - clamav-daemon
       - ubuntu-restricted-extras
       - gstreamer1.0-plugins-bad 
       - gstreamer1.0-plugins-ugly 
       - gstreamer1.0-plugins-good 
       - libavcodec-extra 
       - gstreamer1.0-libav 
       - chromium-codecs-ffmpeg-extra 
       - libdvd-pkg 
       - libfuse2 
       - virtualbox 
       - virtualbox-ext-pack 
       - xclip 
       - gimp 
       - vlc
       - ninja-build
       - gettext
       - cmake
       - unzip
       - build-essential
       - npm
       - python3.11-venv

  # # Make sure that the Applicatons directory is created
  # - name: Create Applications directory
  #   file:
  #    path: "/home/gato/Applications"
  #    state: directory
  #    mode: "0755"

  # Download Joplin 
  - name: Install Joplin
    become: yes
    get_url:
     url: https://objects.joplinusercontent.com/v2.14.20/Joplin-2.14.20.AppImage?source=JoplinWebsite&type=New
     dest: "/home/gato/Applications"
     mode: a+x

  # Download Obsidian
  - name: Install Obsidian
    become: yes
    get_url:
     url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.5.12/Obsidian-1.5.12.AppImage 
     dest: "/home/gato/Applications"
     mode: a+x

  # Download Bitwarden
  - name: Install Bitwarden
    become: yes
    get_url:
     url: https://vault.bitwarden.com/download/?app=desktop&platform=linux
     dest: "/home/gato/Applications"
     mode: a+x

  # # # Make sure that the fonts directory is there
  # # - name: Create fonts directory
  # #   file:
  # #    path: "/home/gato/.local/share/fonts/"
  # #    state: directory
  # #    mode: "0755"
  # # 
  # # This will install the Proto nerd font
  # - name: Download Nerd Font
  #   unarchive: 
  #     src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/0xProto.zip 
  #     dest: "/home/gato/.local/share/fonts/"
  #     remote_src: yes
  #
  # This will refresh the font cache
  - name: Refresh font cache
    shell: fc-cache -f -v

  # Installs zsh if not already installed
  - name: Make sure that zsh is installed
    apt: 
     name: zsh
     state: present
     update_cache: yes
    become: true

  # Switches the default shell to zsh
  # Make sure to log back out and back in
  - name: Make sure zsh is the default shell 
    user:
      name: gato
      shell: "/usr/bin/zsh"
    become: true
    
  # Download Zsh
  - name: Download Oh My Zsh installation script
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install_ohmyzsh.sh

  # Run ZSH install script
  - name: Run Oh My Zsh installation script
    command: sh /tmp/install_ohmyzsh.sh --unattended
    register: ohmyzsh_result
    failed_when: "'FAILED' in ohmyzsh_result.stderr"

  # Copy the .zshrc file to home directory
  - name: copy .zshrc file
    copy: 
     src: files/zshrc
     dest: /home/gato/.zshrc
     owner: gato
     group: gato

  # Copy the tmux-sessionizer to .local/bin
  - name: copy tmux-sessionizer
    copy: 
     src: files/tmux-sessionizer
     dest: "/home/gato/.local/bin/tmux-sessionizer"
     owner: gato
     group: gato

  # Copy the .tmux.conf file to the home directory
  - name: copy .tmux.conf
    copy: 
     src: files/tmux.conf
     dest: /home/gato/.tmux.conf
     owner: gato
     group: gato
