---
# This playbook installs my necessary apt packages
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Installing apt packages
    package: 
      name: 
       - htop
       - git
       - curl
       - tmux
       - tree
       - wget
       - stow
       - python3-psutil
       - clamav
       - clamav-daemon
       - ubuntu-restricted-extras
       - gstreamer1.0-plugins-bad 
       - gstreamer1.0-plugins-ugly 
       - gstreamer1.0-plugins-good 
       - libavcodec-extra 
       - gstreamer1.0-libav 
       - chromium-codecs-ffmpeg-extra 
       - libdvd-pkg 
       - libfuse2 
       - virtualbox 
       - virtualbox-ext-pack 
       - xclip 
       - gimp 
       - vlc
       - ninja-build
       - gettext
       - cmake
       - unzip
       - build-essential
       - npm

  - name: copy .zshrc file
    copy: 
     src: files/zshrc
     dest: /home/gato/.zshrc
     owner: gato
     group: gato

  - name: copy .tmux.conf
    copy: 
     src: files/tmux.conf
     dest: /home/gato/.tmux.conf
     owner: gato
     group: gato

