---
# This playbook installs zsh
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Make sure that zsh is installed
      apt: 
       name: zsh
       state: present
       update_cache: yes
      become: true

    - name: Make sure zsh is the default shell 
      user:
        name: gato
        shell: "/usr/bin/zsh"
      become: true
